# Find Serial if support requested
if(SEGWAYRMP_USE_SERIAL)
  find_package(serial)
  if(serial_FOUND)
    message("-- Building with serial support")
    include_directories(serial_INCLUDE_DIRS)
    list(APPEND SEGWAYRMP_SRCS src/impl/rmp_serial.cc)
    list(APPEND SEGWAYRMP_LINK_LIBS ${serial_LIBRARIES})
    add_definitions(-DSEGWAYRMP_USE_SERIAL)
  else(serial_FOUND)
    message("--")
    message("-- Serial support disabled: Serial library not found.")
    message("--")
  endif(serial_FOUND)
endif(SEGWAYRMP_USE_SERIAL)